# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "taxonomicStatus", # <autocomplete_server>
  "scientificName", # <autocomplete_server>
  "taxonRank", # <autocomplete_app>
  "taxonID", # <fetch_single_parent>
  "parentNameUsageID", # <fetch_single_parent>
  "taxonID", # <fetch_parents>
  "taxonID", # <fetch_synonyms>
  "parentNameUsageID", # <fetch_children_one_level_single>
  "taxonomicStatus", # <fetch_children>
  "taxonID", # <fetch_children>
  "scientificName", # <subset_to_taxon_single>
  "taxonID", # <subset_to_taxon_single>
  "value", # <make_empty_ppg>
  "taxonRank", # <subset_server>
  NULL
))
